<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	let avatarUrl = $derived(
		data.profile.avatar ? `${data.assetsOrigin}/${data.profile.avatar}` : null
	);

	let title = $derived(data.profile.name);
	let description = $derived(
		data.profile.tagline ?? `${data.profile.name} — writing, links and work.`
	);
	let year = new Date().getFullYear();

	// The bare hostname, not the protocol — platform titles read "Injoon Oh —
	// ij5.dev", not "Injoon Oh — https://ij5.dev".
	let siteName = $derived(new URL(data.publicOrigin).hostname);

	// The card shows the name and tagline; the alt mirrors that, without the
	// "Injoon Oh —" that the description fallback already prefixes.
	let ogImageAlt = $derived(
		data.profile.tagline ? `${data.profile.name} — ${data.profile.tagline}` : data.profile.name
	);

	// `<` is the one character that can close the script tag early; everything
	// else in a serialized JSON object is safe inside a data block.
	let jsonLd = $derived(
		{
			'@context': 'https://schema.org',
			'@type': 'Person',
			name: data.profile.name,
			url: data.publicOrigin,
			description,
			...(data.profile.avatar
				? { image: `${data.assetsOrigin}/${data.profile.avatar}` }
				: {}),
			// Only the links a crawler could actually visit — mailto: is not a
			// URL a Person schema can point at.
			sameAs: data.profile.links
				.filter((l) => /^https?:\/\//.test(l.href))
				.map((l) => l.href)
		}
	);
</script>

<svelte:head>
	<title>{title}</title>
	<meta name="description" content={description} />

	<link rel="canonical" href={data.publicOrigin} />

	<meta property="og:type" content="website" />
	<meta property="og:url" content={data.publicOrigin} />
	<meta property="og:site_name" content={siteName} />
	<meta property="og:locale" content="en_US" />
	<meta property="og:title" content={title} />
	<meta property="og:description" content={description} />
	<!-- Generated by `/og.png` from the published profile; `v` bumps on every
	     publish, which busts Twitter and Facebook's own image caches. -->
	<meta property="og:image" content="{data.publicOrigin}/og.png?v={data.v}" />
	<meta property="og:image:width" content="1200" />
	<meta property="og:image:height" content="630" />
	<meta property="og:image:type" content="image/png" />
	<meta property="og:image:alt" content={ogImageAlt} />

	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content={title} />
	<meta name="twitter:description" content={description} />
	<meta name="twitter:image" content="{data.publicOrigin}/og.png?v={data.v}" />
	<meta name="twitter:image:alt" content={ogImageAlt} />

	<!-- Svelte treats the inside of a literal <script> element as raw text, so
	     the whole data block is built as a string instead. `<` is escaped to
	     \u003c so the JSON can never terminate the element early. -->
	{@html `<script type="application/ld+json">${JSON.stringify(jsonLd).replace(/</g, '\\u003c')}</script>`}

	<meta name="theme-color" content="#f5f5f7" media="(prefers-color-scheme: light)" />
	<meta name="theme-color" content="#18181d" media="(prefers-color-scheme: dark)" />

	{#if data.needsScript}
		<script src="/w.js" defer></script>
	{/if}

	<!-- Always, not gated like w.js: the fingerprint is for visitor counting,
	     not for anything on the page that needs a script. `defer` keeps it off
	     the render path; the beacon itself is a single keepalive POST. -->
	<script src="/a.js" defer></script>
</svelte:head>

<main
	class="mx-auto flex min-h-dvh max-w-[42rem] flex-col pt-[clamp(4rem,12vh,7rem)] pr-[max(1.5rem,env(safe-area-inset-right))] pb-[calc(2.5rem+env(safe-area-inset-bottom))] pl-[max(1.5rem,env(safe-area-inset-left))]"
>
	<header class="mb-11">
		{#if avatarUrl}
			<img
				class="mb-[1.15rem] block size-16 rounded-full bg-surface-sunken object-cover"
				src={avatarUrl}
				alt=""
				width="64"
				height="64"
				fetchpriority="high"
			/>
		{/if}
		<!-- text-2xl and text-md carry their own tracking + leading from the type
		     scale, so a display heading never falls back to body leading. -->
		<h1 class="text-2xl font-semibold">{data.profile.name}</h1>
		{#if data.profile.tagline}
			<p class="mt-2 max-w-[40ch] text-md text-text-muted">{data.profile.tagline}</p>
		{/if}
	</header>

	<!--
		The document is authored as Markdown and rendered to HTML on the server;
		there is no untrusted HTML in it (the renderer escapes source markup and
		builds every element itself), so it is safe to inject here. This is the
		whole page body — prose, link buttons, images, the contribution graph.
	-->
	<article class="prose">{@html data.html}</article>

	<footer class="mt-auto pt-16 font-mono text-xs text-text-muted">
		<span>© {year} {data.profile.name}</span>
	</footer>
</main>
